### ISSUE TITLE
removeObsoleteCopies fails on windows due to mixed dir separators

### ISSUE THREAD

**Issue by backbone87** [contao-community-alliance/composer-plugin#10]
das problem hatte ich schon mal vor einer ganzen weile angesprochen und damals auch schon das problem gefunden.
habe heute mal wieder meine lokale testumgebung am laufen gehabt und einen quickfix dafür gebaut. folgendes habe ich vor dem array_diff in https://github.com/contao-community-alliance/composer-plugin/blob/develop/src/ContaoCommunityAlliance/Composer/Plugin/CopyInstaller.php#L130 eingefügt:
`$copies = str_replace(array('/', '\\'), DIRECTORY_SEPARATOR, $copies)`

ich weiß das ist sehr quick'n'dirty, aber tut erstmal

**Comment by discordier** [comment]
Closing as we imply it as fixed
