### ISSUE TITLE
Error handler does strange things

### ISSUE THREAD

**Issue by seaneble** [contao-community-alliance/composer-plugin#14]
Hello,

I noticed strange things when updating an Isotope installation from _2.1.0 RC1_ to _2.1.0_ with  Composer (backend integration) in a PHP 5.4 environment:

1. The Isotope internal upgrade logic is called by the ```RunonceExecutor```
2. Somewhere, this logic asks Contao for ```Environment::scriptName```
3. The method uses bad code:
```php
($_SERVER['ORIG_PATH_INFO'] ? $_SERVER['ORIG_PATH_INFO'] : $_SERVER['PATH_INFO'])
```
This generates a ___PHP Notice___ because one should at least use ```isset``` or ```array_key_exists``` instead of directly accessing non-existent array keys.
4. The notice is picked up by the error handler defined in the class ```RunonceExecutor```
5. The notice ends up on my screen as
<pre>Fatal error: Uncaught exception 'ErrorException' with message 'Undefined index: ORIG_PATH_INFO' in …</pre>

Is this something Composer should handle? Or is the only real solution to fix the bad code in ```Environment::scriptName```? Perhaps someone can enlighten me!

Sebastian

**Comment by BugBuster1701** [comment]
Ist das immer noch nicht behoben?
Contao 3.5.0-RC1, bei Klick auf Pakete aktualisieren massenweise Notice Zeilen auf dem Bildschirm
```Notice: Undefined index: precision...```
```Notice: Undefined index: length```
```Notice: Undefined index: deleteConfirm```
```Notice: Undefined index: dataContainer```
```Notice: Undefined index: ALTER_ADD```
usw.
im Moment von ```do=composer&update=database```
Durch den Einbau von ``` & ~E_NOTICE``` habe ich dann das Update weiter durchführen können.

**Comment by fritzmg** [comment]
Yes, still present and still a problem when updating Isotope.

**Comment by BugBuster1701** [comment]
Please correct this before the Contao 3.5.0 stable release!

**Comment by aschempp** [comment]
Can we fix this asap please? The fix is fairly easy. `RunonceExecutor::handleError` must look like this:

```php
public function handleError($errno, $errstr, $errfile, $errline)
{
    if ($errno & E_NOTICE || $errno & E_STRICT || $errno & E_DEPRECATED) {
        return;
    }

    throw new \ErrorException($errstr, 0, $errno, $errfile, $errline);
}
```

This will restore the default core behavior.

**Comment by aschempp** [comment]
Ok that if-method doesnt seem to do the trick, but I'm pretty sure @discordier can come up with the right patch :-)

**Comment by BugBuster1701** [comment]
Der Fix #42 wurde bereits gemerged in den develop Brunch. Muss "nur" noch ne neue Master kommen :-)
Laut Tags wäre das dann mittlerweile die 2.3.5

**Comment by BugBuster1701** [comment]
Bzw. zu packagist.org, wenn ich das richtig sehe hat der Master Brunch die 2.3.5, aber auf packagist.org gibt es nach wie vor nur die 2.3.3

**Comment by discordier** [comment]
Apparently the notification between packagist and github was broken somehow. I just forced a manual sync and the new version is now available.

**Comment by BugBuster1701** [comment]
:+1:
