### ISSUE TITLE
Write journal file

### ISSUE THREAD

**Issue by tristanlins** [contao-community-alliance/composer-plugin#25]
The plugin log the activities into a separate `journal.json`:

``` json
{
    "vendor/name": [
        { "type": "install",   "version": "1.0",                            "date": "2014-10-13T14:56:00+02:00" },
        { "type": "update",    "version": "1.1", "previous-version": "1.0", "date": "2014-10-13T14:56:00+02:00" },
        { "type": "uninstall", "version": "1.1",                            "date": "2014-10-13T14:56:00+02:00" }
    ]
}
```

This could be done through the [post install](https://github.com/composer/composer/blob/master/src/Composer/Script/ScriptEvents.php#L86-L93), [post update](https://github.com/composer/composer/blob/master/src/Composer/Script/ScriptEvents.php#L104-L111) and [post uninstall](https://github.com/composer/composer/blob/master/src/Composer/Script/ScriptEvents.php#L122-L129) events.

See my comment here: https://github.com/contao-community-alliance/composer-client/issues/200#issuecomment-58889041

**Comment by discordier** [comment]
Will not implement, it simply is not working and not worth the hassle
