### ISSUE TITLE
is_link does not work correct under php with windows

### ISSUE THREAD

**Issue by Zeromax** [contao-community-alliance/composer-plugin#34]
The Problem is, that the `is_link` returns always `false`.

That is realy weird. So I haven't found a usefull solution for now. Any Ideas?

**Comment by fritzmg** [comment]
> If target is a Folder realpath returns false.

Are you sure about that? In my testing `realpath` on a real folder returns just the path to that folder, not false.

**Comment by Zeromax** [comment]
I think that this is also resolved by using php-fcgi on xampp:
https://github.com/contao/core-bundle/issues/208#issuecomment-138114929
