### ISSUE TITLE
Plugin pollutes non contao-module packages

### ISSUE THREAD

**Issue by dmolineus** [contao-community-alliance/composer-plugin#37]
I have a package which has the type `library`. When calling `composer update` the composer-plugin (also the client, I don't know) modifies the `composer.json`. The library itselfs has no dependency of the composer plugin but requires another package which requires the plugin.

Following changes are made:
- Add legacy and package repository. The added package repository stops Composer to work as the directory does not exist.
- Adds components path.
- Reformats the composer.json

**Comment by discordier** [comment]
The problem does not exist in 3.0 anymore.
