### ISSUE TITLE
Plugin does not support composer repository-type path

### ISSUE THREAD

**Issue by cboelter** [contao-community-alliance/composer-plugin#47]
I tired to use type: "path" for using my git-repository as an symlink, for the vendor folder it works fine, but the system/modules ordner is not linked correctly. It inlcudes the absolute path to the repo. 

Any idea?

**Comment by discordier** [comment]
Can you elaborate this a little?

**Comment by discordier** [comment]
Is the problem still existing in 3.0.4?
If not, I'm tempted to close this.
