### ISSUE TITLE
composer-plugin can destroy a contao installation

### ISSUE THREAD

**Issue by fritzmg** [contao-community-alliance/composer-plugin#49]
If a package is installed/required via the Contao package manger (or manually via `composer update`) which has the following data in its composer.json:
```
"extra":{
	"contao":{
		"sources": {
			"src":""
		}
	}
}
```
(or similar) the `composer-plugin` will "self destruct" the Contao installation, i.e. it will (try to) delete the content of the __whole__ Contao installation.

I can post testing instructions if necessary.

**Comment by discordier** [comment]
See #38.

**Comment by fritzmg** [comment]
Ah sorry, didn't notice.
