### ISSUE TITLE
[2.4] contao/core-bundle locking

### ISSUE THREAD

**Issue by aschempp** [contao-community-alliance/composer-plugin#50]
The release/2.4 version allows to lock the core-bundle when displaying dependencies. That should not be possible.

**Comment by discordier** [comment]
This is an issue of the client. It has nothing to do with the plugin.

**Comment by aschempp** [comment]
You’re right

**Comment by discordier** [comment]
Ref: https://github.com/contao-community-alliance/composer-client/issues/275
