### ISSUE TITLE
composer-plugin tries to put a runonce.php into app/Resources/contao/config

### ISSUE THREAD

**Issue by fritzmg** [contao-community-alliance/composer-plugin#52]
I tried to make one of my extensions installable in Contao 3 as well as Contao 4 for the first time. I added/changed the `composer.json` of the extension package accordingly:
```
"contao/core-bundle":"~3.0 || ~4.1",
"contao-community-alliance/composer-plugin":"~2.4 || ~3.0"
```
then required it in the `composer.json` of the Contao 4.1 installation. When running a `composer update` afterwards, the following error happens:
```
[ErrorException]
file_put_contents(C:\xampp\htdocs\c41dev/app/Resources/contao/config/runonce.php): failed to open stream: No such file or directory
```
For some reason the `composer-plugin` tries to put a `runonce.php` into `app/Resources/contao/config` which makes no sense of course. I don't even know if that is supposed to be the `runonce.php` from my extension. The `composer.json` of my extension has the following defined:
```
"extra":{
	"contao":{
		"sources":{
			"system/modules/inherit_article":"system/modules/inherit_article"
		},
		"runonce":[
			"system/modules/inherit_article/runonce/runonce.php"
		]
	}
}
```
See [fritzmg/contao-inherit-article/blob/master/composer.json](https://github.com/fritzmg/contao-inherit-article/blob/master/composer.json).

Full console ouptut:
```
# composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing contao-community-alliance/composer-plugin (3.0.0)
    Loading from cache

  - Installing fritzmg/contao-inherit-article (dev-master e568929)
    Loading from cache

Writing lock file
Generating autoload files


  [ErrorException]
  file_put_contents(C:\xampp\htdocs\c41dev/app/Resources/contao/config/runonce.php): failed to open stream: No such file or directory


update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--with-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--] [<packages>]...
```

**Comment by aschempp** [comment]
Yes this is intentional. As Contao will only execute `runonce.php` if they are located in your module's config folder, we need a wrapper that executes the files defined in your composer.json. That wrapper is putting a `runonce.php` in `App/Resources/config/config` for it to be executed.

Is there a write permission issue to put the file in place?

**Comment by fritzmg** [comment]
`file_put_contents` fails because the directory `app/Resources/config/config` simply does not exist. It does not create the directory structure automatically, you have to do that with `mkdir(…, …, true)` yourself.

**Comment by fritzmg** [comment]
That's why I originally thought `app/Resources/contao/config` is the wrong path, since that directory does not exist and so far I haven't seen another Symfony application (I think), which puts anything like that into the `/app` directory.

But Contao does indeed look for `runonce.php` files there:
```php
$files = \System::getContainer()->get('contao.resource_locator')->locate('config/runonce.php', null, false);
```
https://github.com/contao/core-bundle/blob/4.1.0/src/Resources/contao/classes/Backend.php#L254

```php
if (is_dir($rootDir . '/app/Resources/contao')) {
    $paths[] = $rootDir . '/app/Resources/contao';
}
```
https://github.com/contao/core-bundle/blob/4.1.0/src/DependencyInjection/Compiler/AddResourcesPathsPass.php#L51

**Comment by aschempp** [comment]
Should be fixed with https://github.com/contao-community-alliance/composer-plugin/commit/fb28dcdde36a09fe0d3b4b51f088b85ee711547a

@discordier please review, merge and publish.

**Comment by fritzmg** [comment]
Seems to work as far as I have tested it :)
