### ISSUE TITLE
Regression of #43

### ISSUE THREAD

**Issue by discordier** [contao-community-alliance/composer-plugin#58]
@aschempp I guess with your rewrite of the plugin we now have a regression of #43 here.
Symlinks from source will not get detected and skipped.

I think we still need this check.

However, as you are now only symlinking the top levels (and not file wise anymore), contained symlinks will pass undetected and therefore might break.

Am I correct on this one?

**Comment by aschempp** [comment]
I think what @ausi does in his extensions is simply not supported. If your extension is Contao 3, then use the Contao 3 structure and copy them to system/modules. There's no need for symlinks…

**Comment by discordier** [comment]
I know and I do not want to support it.
Quite the opposite, the 2.4 version detected his dangerous approach and REFUSED to create symlinks where the source are symlinks.

The new version does NOT detect this and happily symlinks the stuff over and therefore potentially links bullshit (not so bad) or even links to some security relevant locations (pretty bad).

My idea was to recursively scan the link source for contained links and if there should happen to be some, refuse to link it over to system/modules (like the old version did).

**Comment by aschempp** [comment]
so you want to fix a problem that we don't want to support? …

**Comment by discordier** [comment]
No, I want to ensure that data that MUST NOT get symlinked does not get symlinked.
Because before it was (for obvious reasons) forbidden and NOW you allow it.

**Comment by discordier** [comment]
Yes, it is a new major Version and if we wouldn't encourage people to allow for BOTH versions (as your design approach to suggests to show how to be compatible between both, Contao 3 and Contao 4) there wouldn't be anything wrong with this.
However, we are encouraging people to do exactly this and therefore we allow bad installation in Contao 4 where we prevent bad installation in Contao 3. Apparently you do not see anything wrong with this?
