### ISSUE TITLE
Composer update wirft DuplicateContaoException

### ISSUE THREAD

**Issue by cboelter** [contao-community-alliance/composer-plugin#60]
Hi zusammen,

bisher lief der Composer bei unserer Installation von Contao 3.4.5 ohne Probleme. Jetzt bekomme ich bei einem composer update immer folgende Meldung:

`[ContaoCommunityAlliance\Composer\Plugin\DuplicateContaoException]
  Warning: Contao core 3.5.15 was about to get installed but 3.4.5 has been found in project root, to recover from this problem please restart the operation
`
Soweit ich gesehen habe, hat sich an den Abhängigkeiten bei uns nichts geändert. Einzige besonderheit ist folgendes:

` - Updating contao/core-bundle (3.4.5) to contao/core-bundle (3.5.15)`

Das ist mir bisher nie aufgefallen. Jemand eine Idee wie ich das Problem lösen kann?

**Comment by aschempp** [comment]
Hast du den Text mal gelesen?

to recover from this problem please restart the operation

**Comment by cboelter** [comment]
Ja habe ich ... ich habe das Update auch mehr als einmal ausgeführt, hat aber nichts gebracht.

**Comment by cboelter** [comment]
Ich habe es jetzt mit folgendem Hinweis gelöst: https://community.contao.org/de/showthread.php?57346-Contao-Core-wird-als-Installation-angezeigt&p=371974&viewfull=1#post371974
