### ISSUE TITLE
[2.4] Post Install Command is not handled 

### ISSUE THREAD

**Issue by Toflar** [contao-community-alliance/composer-plugin#63]
The housekeeping and runonce stuff is currently only handled on the post update event.
It should, however, also run when you run `composer install`.

See https://github.com/contao-community-alliance/composer-plugin/blob/support/2.4/src/ContaoCommunityAlliance/Composer/Plugin/Plugin.php#L137

**Comment by aschempp** [comment]
This was probably never noticed because the composer client does only do `update`…

**Comment by discordier** [comment]
V3 does not do any of the maintenance tasks needed in V2.4, therefore it naturally is not affected. :smile_cat:
