### ISSUE TITLE
plugin keeps readding superfluous legacy repository path

### ISSUE THREAD

**Issue by fritzmg** [contao-community-alliance/composer-plugin#64]
As of version `0.16.4`, the `composer-client` initializes the `composer.json` with the following information for the legacy repository:
```
{
    "type": "composer",
    "url": "https?://legacy-packages-via.contao-community-alliance.org",
    "allow_ssl_downgrade": false
}
```
https://github.com/contao-community-alliance/composer-client/blob/0.16.4/src/system/modules/!composer/src/Runtime.php#L84-L88

However, the `composer-plugin` always adds
```
{
    "type": "composer",
    "url": "https://legacy-packages-via.contao-community-alliance.org/"
}
```
when not present. So if you remove those lines, next time you do a composer update the `composer-plugin` will add it again.

**Comment by discordier** [comment]
Sadly we can not remove this adding of the repo and all manipulation of the composer.json within a minor release, can we?
In version 3, this is all gone.
IMO we might be able to remove the repository settings if no legacy-packages are mentioned in the require section anymore.

What do the others think about this? /cc @aschempp, @toflar?

**Comment by aschempp** [comment]
Well I don't see why both the client and the plugin must add these lines. I think they should be removed from the client and the plugin should add the new URL. Nothing fancy, no problem for a patch release?

**Comment by fritzmg** [comment]
The client does not 'add' these lines. The client initializes the whole composer.json in the first place.

**Comment by discordier** [comment]
@aschempp I was talking about making the plugin aware if the line is needed and removing it if not needed anmyore.
The bootstrapping in the client has to remain however.

**Comment by aschempp** [comment]
I don't get it. Why would the plugin need something different than the client? And the plugin already checks if it's settings is there and only adds if not…

**Comment by discordier** [comment]
I AM TALKING ABOUT MAKING THE PLUGIN REMOVE THE REPOSITORY IF NOT IN USE ANYMORE!!!!

As soon as there is not a single `contao-legacy/*`package mentionend anymore, the repository does not have to get added at all.
And, the plugin does not need anything on its own, as adding the repository from the plugin is way too late as it will only get installed when resolving has already been done but that will fail if the repository is not present.
So the repository needs to get added from within the client.

**Comment by fritzmg** [comment]
This problem exists even with the newest version of the `composer-client`. The `composer-client` initializes the `composer.json` with
```
        {
            "type": "composer",
            "url": "https://legacy-packages-via.contao-community-alliance.org"
        },
```
but the `composer-plugin` adds
```
        {
            "type": "composer",
            "url": "https://legacy-packages-via.contao-community-alliance.org/"
        },
``` 
(with a slash at the end)
