### ISSUE TITLE
Ergonomics of the composer is not self-explanatory

### ISSUE THREAD

**Issue by FredTheFrog** [contao-community-alliance/composer-plugin#65]
Today I installed the composer and I do not find it as self-explanatory as I am used to from Contao. When I choose a package for installation it is afterwards red in the version shown instead of green.
The user doesn't know why:
1. Is it because it is not installed?
2. Is it because installation went wrong?
3. Is it because a non stabile version has been chosen?
Maybe we can add a title to the version number which shows the reason for the marking when we have a mouseover.
Contao: 3.5.21
Composer: 0.14
![screenshot](https://cloud.githubusercontent.com/assets/2742031/22295763/61d60714-e318-11e6-8335-8352bd68d2db.png)

**Comment by aschempp** [comment]
You're probably referring to the Composer Client (https://github.com/contao-community-alliance/composer-client) not the Plugin.

**Comment by FredTheFrog** [comment]
Of course! I am sorry. Will close it here.
