### ISSUE TITLE
Versionsnummern - Falsche Reihenfolge

### ISSUE THREAD

**Issue by comolo** [contao-community-alliance/composer-plugin#66]
Hallo,

wenn ich mein Plugin Supertheme (comolo/contao-supertheme) über den Composer installieren möchte, werden die Versionen nicht in der richtigen Reihenfolge angezeigt. Bsp: 2.2.5 vor 2.3.1
 
![bb16ac54-f2a7-11e6-9647-2f4ff115133d](https://cloud.githubusercontent.com/assets/1228676/22931594/81ebeb1a-f2c5-11e6-9728-97bb9c8e5bc3.png)

**Comment by aschempp** [comment]
Das Backend ist der Composer Client (https://github.com/contao-community-alliance/composer-client), bitte das Ticket dort neu erstellen.
