### ISSUE TITLE
 [3.X] Bringing back folder copy for extra:contao:files/userfiles

### ISSUE THREAD

**Issue by denniserdmann** [contao-community-alliance/composer-plugin#68]
In Contao 3, i used composer to copy a folder to `files`, which the user could change without being afraid that composer will override changed files, see http://de.contaowiki.org/Composer/Tutorial:_Extension_für_Composer_fit_machen#Contao_Konfiguration

Now, in Contao 4 this Function is not working anymore. I get an error instead 

```
[ErrorException]
  copy(): The first argument to copy() function cannot be a directory
```

Problem is also discussed here: https://community.contao.org/de/showthread.php?66821-Contao-4-Erweiterung-Dateien-nicht-überschreiben&p=441471

Is there a chance to bring this feature back to composer-plugin?

**Comment by fritzmg** [comment]
> Now, in Contao 4 this Function is not working anymore. I get an error instead

To clarify: this error happens because you are trying the `"extra"` option `"userfiles"` instead now, since the `"files"` option only existed in `composer-plugin` `2.x` and Contao 4 requires `3.x`.

**Comment by aschempp** [comment]
`userfiles` is the correct name according to the README: https://github.com/contao-community-alliance/composer-plugin/tree/support/2.4#userfiles

Using `files` is probably just a BC-leftover in version 2, but we removed BC in v3 (that's why it's a new major 😉 )

**Comment by fritzmg** [comment]
@aschempp with the (old) `files` option you were able to define whole directories to be copies. With the `userfiles` option that does not work anymore. It only supports individual files, not whole folders.

**Comment by aschempp** [comment]
Can you try the `hotfix/3.0.6` branch?

**Comment by denniserdmann** [comment]
@aschempp looks good. folder is copied into `files` and won't be removed when uninstalling package.

**Comment by bezin** [comment]
What is the status on this issue? Anything where I may contribute? Would love to use the Nutshell starterkit in Contao 4 :)

**Comment by denniserdmann** [comment]
same here ;-)

**Comment by aschempp** [comment]
I have release 3.0.6
