### ISSUE TITLE
Contao 4: Copy files outside files-folder with composer

### ISSUE THREAD

**Issue by denniserdmann** [contao-community-alliance/composer-plugin#74]
In #68, we were talking about adding static files (not symlinks) to the files folder. Now i'm looking for a way to copy files to a folder outside of `files`, for example into `templates` or even to the root (for files like package.json, gulpfile.js).

In Contao 3.5 it doesn't matter, where you want to add your files, but in C4 this isn't working anymore. Is there a chance, that this function is coming back or is it forbidden because of security reasons? If it won't come back, do you have a recommendation how to solve this issue?

**Comment by aschempp** [comment]
What do you mean it didn't matter in Contao 3.5?

**Comment by denniserdmann** [comment]
In Contao 3.5 i am able to copy a file to from a repository into `root` or `/templates`

**Comment by aschempp** [comment]
How do you copy instead of symlink in 3.5?

**Comment by fritzmg** [comment]
> In Contao 3.5 i am able to copy a file to from a repository into root or /templates

It probably does not make any sense to copy templates into the `/templates` folder. And in Contao 4 there shouldn't be any requirement to copy anything else anywhere anymore. What exactly do you want to achieve?

> How do you copy instead of symlink in 3.5?

That's the default behavior.

**Comment by denniserdmann** [comment]
I was using composer to install our nutshell framework kit, a boilerplate that, once installed, can be modified by the user (that why i copy instead of symlink).

I liked the idea to install a boilerplate via composer, but it looks like downloading and copying files by hand is now the only way to install the kit. 

For more details, check: https://github.com/ErdmannFreunde/euf_nutshell_kit/issues/2

**Comment by fritzmg** [comment]
I think your use case is better done with a composer boiler plate. There you can pre-populate anything you want.

**Comment by aschempp** [comment]
Well a user can always edit the templates of an extension, why would you need to copy them to the root folder?

**Comment by denniserdmann** [comment]
@aschempp sorry for the misunderstanding. 
I don't want to copy templates to root. I want to copy templates to the templates-folder and files like a gulp file.js or package.json to the root-folder. But as @fritzmg said, maybe the better way is to create a project boiler plate. 

@fritzmg Do you know good resources how to create a project boiler plate?
