### ISSUE TITLE
Contao 4.6.0-RC1 und contao-community-alliance/composer-plugin

### ISSUE THREAD

**Issue by squidi** [contao-community-alliance/composer-plugin#76]
bei der Installation von Erweiterungen, egal ob über Manager oder Console, die als Abhängigkeit 

Code: "contao-community-alliance/composer-plugin":"~2.4 || ~3.0"

beinhalten, können diese nicht installiert werden, weil stehst versucht wird, die Version 2.4.3 zu laden, diese ist aber nicht kompatibel.

siehe auch => [https://community.contao.org/de/showthread.php?71412-Contao-4-6-0-RC1-und-contao-community-alliance-composer-plugin](https://community.contao.org/de/showthread.php?71412-Contao-4-6-0-RC1-und-contao-community-alliance-composer-plugin)

**Comment by fritzmg** [comment]
This is because Contao 4.6 is compatible to Symfony 4, while `contao-community-alliance/composer-plugin:^3.0` is not compatible or unlocked for Symfony 4 and `contao-community-alliance/composer-plugin:^2.0` does not have any conflicts or dependencies regarding Symfony or Contao.

**Comment by aschempp** [comment]
Fixed with #77, thanks @fritzmg
