### ISSUE TITLE
Contao 3.5.36 can't install composer

### ISSUE THREAD

**Issue by xApep** [contao-community-alliance/composer-plugin#79]
Hi. I'm using Windows and WAMP. Is there any requirement to install composer (I have installed composer via windows setup)?

When I click Install composer, nothing happens.

![image](https://user-images.githubusercontent.com/1315340/46421531-91033980-c732-11e8-9896-54fd2260783a.png)

Thanks.

**Comment by fritzmg** [comment]
This issue is probably more for the composer-client, not the composer-plugin.

**Comment by xApep** [comment]
Thanks. Moved to [#317](https://github.com/contao-community-alliance/composer-client/issues/317)
