### ISSUE TITLE
Update for Composer v2

### ISSUE THREAD

**Issue by Toflar** [contao-community-alliance/composer-plugin#81]
See composer/composer#8726

**Comment by aschempp** [comment]
I have added experimental support in 54b6f5fd7ab71afd53a5bf55b33633be75c5d4db

**Comment by fritzmg** [comment]
> I have added experimental support in [54b6f5f](https://github.com/contao-community-alliance/composer-plugin/commit/54b6f5fd7ab71afd53a5bf55b33633be75c5d4db)

Seems to work fine 👍 :)

**Comment by aschempp** [comment]
Released as version 3.1.0
