### ISSUE TITLE
Unlock/test for Symfony 5

### ISSUE THREAD

**Issue by fritzmg** [contao-community-alliance/composer-plugin#84]
When installing a Contao 3 extension in a fresh Contao 4.11+ installation, a downgrade to Symfony 4 is necessary, since `contao-community-alliance/composer-plugin` still requires its Symfony dependencies in version `^4.0` at most. This makes the first installation of Contao 3 extensions in Contao 4.11 for not so savvy users more difficult. If possible the allowed versions for the finder and process components should be expanded to `^5.0`.

I'll test when I have the time and see if any changes would be necessary.

**Comment by aschempp** [comment]
@fritzmg would be good if you can figure this out. We're not using a lot of Sf methods so I guess it should be a matter of expanding the constraints.

**Comment by fritzmg** [comment]
This would need to be adjusted, since the first parameter must be an array in Symfony 5 (and a string in Symfony 2.7):

https://github.com/contao-community-alliance/composer-plugin/blob/bddeff9af32b7f271afb7814d8c94a80fe7b32c8/src/UserFilesLocator.php#L99

However, I just noticed that the `UserFilesLocator` probably does not work at all in the Contao Managed Edition? It will probably always throw an exception here:

https://github.com/contao-community-alliance/composer-plugin/blob/bddeff9af32b7f271afb7814d8c94a80fe7b32c8/src/UserFilesLocator.php#L73-L88

Not sure if this is really worth fixing just for the sake of Symfony 5 compatibility? 😁

**Comment by fritzmg** [comment]
Draft PR: #85

**Comment by aschempp** [comment]
I started a new minor version (3.2) in https://github.com/contao-community-alliance/composer-plugin/commit/db4bef0da2e10025a4678feca0a48589dc0e005c that drops support for anything older than Contao 4.9.

However:
 1. I don't think we should fix the UserFilesLocator, or at least that's not related to this stuff. If it hasn't been an issue the last few years, I wouldn't bother playing with it …
 2. Regarding the process stuff (also in `UserFilesLocator`), be aware that the process component is (afaik) always used from Composer, so it won't be the local Symfony 5 one, right?

Maybe you can test if db4bef0da2e10025a4678feca0a48589dc0e005c already works fine with everything?

**Comment by fritzmg** [comment]
Seems to work fine. Though personally I would not drop Composer 1.x yet (we still have projects that cannot be used with Composer 2.x - but those are not Contao 4.11, so that's fine) and increase the Symfony requirement to `^5.2`, as the other versions are EOL and thus dependency resolving can potentially be improved.

> 2. Regarding the process stuff (also in `UserFilesLocator`), be aware that the process component is (afaik) always used from Composer, so it won't be the local Symfony 5 one, right?

Yeah... that's still something that Composer should fix imho... it's very unreliable and a pain to code with. My code change would work with all Symfony versions.

**Comment by aschempp** [comment]
> Though personally I would not drop Composer 1.x yet (we still have projects that cannot be used with Composer 2.x - but those are not Contao 4.11, so that's fine) 

Composer 1 would still work with the plugin v3.1, which works fine with Contao 4.9. I don't think one should use Composer 1 with Contao 4.11.

> and increase the Symfony requirement to ^5.2, as the other versions are EOL and thus dependency resolving can potentially be improved.

Since Contao 4.11 only supports Symfony 5.2, and not other Contao version supports Symfony 5, that might make sense. I don't think it will improve performance though.

**Comment by aschempp** [comment]
Updated in 5ba25a846ccf69344ae72d142488de0a1945b2d2 and release 3.2.0. Btw. the 3.2.0 bump is mostly so we could release patch-updates to 3.1 if necessary for whatever reason.
